puts "The students of Villians Academy"
puts "______________"
puts "Dr. Hannibal Lectur"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex Delarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
print "Overall, we have "
print 11
puts " great students"
